export {default as About} from './about/About'
export {default as Blog} from './blog/Blog'
export {default as Features} from './features/Features'
export {default as Footer} from './footer/Footer'
export {default as Header} from './header/Header'
export {default as Services} from './our_services/Services'
export {default as Testimonials} from './testimonials/Testimonials'